# Generated by Django 5.0.3 on 2024-03-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['index']},
        ),
    ]
