# Generated by Django 5.0.3 on 2024-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=10),
        ),
    ]
