# Generated by Django 5.0.3 on 2024-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
