# Generated by Django 5.0.3 on 2024-03-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='order',
            new_name='index',
        ),
    ]
