# Generated by Django 5.0.3 on 2024-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_order_message_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
