# Generated by Django 5.0.3 on 2024-03-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.TextField(),
        ),
    ]
